services:
    bot:
        build: .
        env_file: ".env"
        environment:
            DB_PATH: "/var/lib/wordle-tracker/data/"
        volumes:
            - wordle_data:/var/lib/wordle-tracker/data/
        depends_on:
            migrator:
                condition: service_completed_successfully
    migrator:
        build: .
        environment:
            DB_PATH: "/var/lib/wordle-tracker/data/"
        volumes:
            - wordle_data:/var/lib/wordle-tracker/data/
        entrypoint: ["python", "manage.py", "migrate", "--noinput"]

volumes:
    wordle_data:
