# Generated by Django 5.2.6 on 2025-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WordleChannel",
            fields=[
                ("channel_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("last_seen_message", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WordleGame",
            fields=[
                ("message_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("guild_id", models.BigIntegerField()),
                ("channel_id", models.BigIntegerField()),
                ("timestamp", models.DateTimeField()),
                ("game_number", models.IntegerField()),
                ("is_win", models.BooleanField()),
                ("is_hard_mode", models.BooleanField()),
                ("guesses", models.IntegerField()),
                ("result", models.JSONField(default=list)),
            ],
        ),
    ]
