# Generated by Django 5.2.6 on 2025-10-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordlegame",
            name="is_duplicate",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
