# Generated by Django 5.2.6 on 2025-10-09 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_wordlegame_is_duplicate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wordlegame",
            old_name="timestamp",
            new_name="posted_at",
        ),
        migrations.AddField(
            model_name="wordlegame",
            name="scanned_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 9, 16, 2, 10, 233087, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
    ]
