# Generated by Django 5.2.6 on 2025-10-17 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_timestamp_wordlegame_posted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordlegame",
            name="channel_id",
        ),
        migrations.RemoveField(
            model_name="wordlegame",
            name="guild_id",
        ),
        migrations.AddField(
            model_name="wordlechannel",
            name="daily_summary_enabled",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wordlechannel",
            name="guild_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="wordlegame",
            name="channel",
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to="core.wordlechannel"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wordlechannel",
            name="last_seen_message",
            field=models.BigIntegerField(null=True),
        ),
    ]
