# Generated by Django 5.2.6 on 2025-10-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_wordlegame_channel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlechannel",
            name="guild_id",
            field=models.BigIntegerField(),
        ),
    ]
