# Generated by Django 5.2.6 on 2025-10-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_wordlechannel_guild_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordlegame",
            name="is_correct_day",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
