# Generated by Django 5.2.6 on 2025-10-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_wordlegame_is_correct_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordlegame",
            name="game_number",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="wordlegame",
            name="user_id",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
