# Generated by Django 5.2.6 on 2025-11-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_wordlegame_game_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlechannel',
            name='daily_reminder_enabled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
